### ISSUE TITLE
missing dbSNP reference for 12-57961409-G-A

### ISSUE THREAD

**Issue by sorensjm** [konradjk/exac_browser#132]
I was browsing to http://exac.broadinstitute.org/variant/12-57961409-G-A and the dbSNP annotation says "Not found in dbSNP".

However, as far as I can see, this variant has been reported as rs199624091 starting with dbSNP build 137.  It was submitted as part of the CSAgilent study (and the frequency there matches well with what ExAC is seeing).

Great job on this browser and the data set release!  I work in an NGS clinical sequencing laboratory, and we're finding these variant frequencies do well to correct errors in earlier data sets and are clearly providing the best source of population frequency estimates.

**Comment by konradjk** [comment]
We have loaded in dbSNP 142 in the most recent update and this appears to be working properly now
