### ISSUE TITLE
Public availablity of test import data

### ISSUE THREAD

**Issue by andrewjesaitis** [konradjk/exac_browser#145]
In the README it looks like a tar file is being copied into the `exac_test_data` from `tin` which I assume is an internal server. Would it be possible to put `exac_browser.tar.gz` somewhere publically accessible. Alternatively, if just a subset of the data was made available that'd be great too. I'm mostly just curious what form the INFO field takes in the sites VCF and what the coverage files look like.

Thanks!

**Comment by konradjk** [comment]
The data files are now available in the link provided.
