### ISSUE TITLE
Incorrect SNPs associated with position (off by 1 bp)

### ISSUE THREAD

**Issue by sharrison6** [konradjk/exac_browser#158]
The rs# number for variants are incorrect - the rs# provided is for the position 1 bp over.
For example:
Variant http://exac.broadinstitute.org/variant/11-76916520-C-T 
The rs# listed is rs372768607. However this rs# is for position 11-76916521 (off by 1 nt)
Additionally,
Variant http://exac.broadinstitute.org/variant/11-2608844-C-T
The rs# listed is rs199472774. However this rs# is for position 11-2608845 (off by 1 nt)

**Comment by a113n** [comment]
We believe the error happens in the below record as well:
http://exac.broadinstitute.org/variant/14-91787600-C-T

**Comment by konradjk** [comment]
We have fixed these with the most recent update
