### ISSUE TITLE
ExAC data source

### ISSUE THREAD

**Issue by imagineyd** [konradjk/exac_browser#162]
Hello :)

Thanks so much this amazing website! It's really cool and useful website to my research.

I have one question about ExAC dataset.
I checked "Contributing projects" of ExAC. Then, can I find data source of variants? 
I want to know my interest variants come from 1000 genomes or TCGA or somewhere.

From your website, I can find information about allele frequencies but I couldn't find the original data source of variants.
If it possible that I can get some information that how can you calculate allele frequencies from original data set?

If you tell me some information about this, it's really big help to me :)

Thanks so much !

**Comment by a113n** [comment]
I think this is an important feature too. In particular, there are some variants in ExAC DB that are not found in dbSNP, 1000 Genome, and ESP6500, yet having a high MAF in ExAC. Allowing users to pinpoint the source of such variants would help us judge whether these variants are simply polymorphisms.

**Comment by konradjk** [comment]
Unfortunately, we do not have permission to release this information, as each project has differing levels of permissions to release data. Since we cannot do this at this time, I'm going to close this issue for now.
