### ISSUE TITLE
INFO NCC interpretation

### ISSUE THREAD

**Issue by dwaggott** [konradjk/exac_browser#166]
Hello!

Should the NCC INFO tag be bounded by the number of samples (i.e. < 60,000)? I was a bit confused how to interpret it. I can see values > 80,000.

`##INFO=<ID=NCC,Number=1,Type=Integer,Description="Number of no-called samples">`

**Comment by monkollek** [comment]
~92K samples were joint called and 60K were used in the release. This metric was not updated on subsetting.

**Comment by dwaggott** [comment]
Excellent!

On a related note, I was trying to calculate the mean depth for a position
via DP/AN/2. Does that make sense? The values I was getting were much lower
than what was on the website i.e. 50 vs 100x.
