### ISSUE TITLE
http://www.broadinstitute.org/~konradk/exac_browser/exac_browser.tar.gz : 404 Not found.

### ISSUE THREAD

**Issue by lindenb** [konradjk/exac_browser#168]
Hi,
for your information: the doc says:

> First (as this can run in parallel), get the datasets that the browser uses and put them into an 'exac_data' directory:
> wget http://broadinstitute.org/~konradk/exac_browser/exac_browser.tar.gz .

but http://www.broadinstitute.org/~konradk/exac_browser/exac_browser.tar.gz currently returns a 404.

> The requested URL /~konradk/exac_browser/exac_browser.tar.gz was not found on this server.

**Comment by konradjk** [comment]
Yes, we are aware of this issue (see issue #145). However, I must ask: are you trying to clone the system? If you just want to use it to query variants, we have an implementation up and running at: http://exac.broadinstitute.org/

If you truly want to run your own webserver, we will be putting this file up soon (in the meantime, you can look at most of the source data on our FTP site at ftp://ftp.broadinstitute.org/pub/ExAC_release)

**Comment by lindenb** [comment]
>  I must ask: are you trying to clone the system?

yes. I want to see if we can use the code for our local VCF.

I'll look at the FTP site

Thank you for the help.
