### ISSUE TITLE
Mean Depth Calculation

### ISSUE THREAD

**Issue by dwaggott** [konradjk/exac_browser#169]
I was trying to calculate the mean depth for a position via DP/AN/2. Does that make sense? The values I was getting were much lower than what was on the website.

For example:
rs12021720 has ~100 dp in the browser but I calculate ~60x from the vcf (14283749/121412/2).

**Comment by konradjk** [comment]
That is one reasonable way to calculate depth, yes. We provide full coverage files on the FTP site (ftp://ftp.broadinstitute.org/pub/ExAC_release/current/coverage), but note that these are capped at 100X.

For your calculation, it would be DP/(AN/2) (depth divided by number of individuals), in which case this would be ~235X (and the browser will cap it at 100X which is what you see there). I'll close this issue for now, feel free to re-open if you find any inconsistencies.

**Comment by dwaggott** [comment]
Thanks!

On Tue, Mar 3, 2015 at 11:10 AM, Konrad Karczewski <notifications@github.com
