### ISSUE TITLE
TTN?

### ISSUE THREAD

**Issue by lestergb** [konradjk/exac_browser#175]
Titin, or TTN, when searched for from the gene/transcript search window, returns a 404 not found error

**Comment by diannafisk** [comment]
Still broken. I've tried different browsers & different internet connections, as well as both querying in the search window and changing the URL.

As the largest protein, and one that typically has a lot of variation, I'd guess that this would be your edge case for the largest amount of variants/gene. If there was one gene that would break your system, this might be it. But still, I'd LOVE to be able to access the data. Can you fix this edge case, please?

Thanks!

-Dianna

**Comment by konradjk** [comment]
Unfortunately, we have not yet found a solution to displaying TTN that does not crash every browser we've tried. It's supposed to go to a special TTN landing page, but that seems to have been broken (just fixed it). We will continue exploring options for this, but for now, we have no good solution.
