### ISSUE TITLE
Adjusted count values

### ISSUE THREAD

**Issue by lsantome** [konradjk/exac_browser#176]
Hi,

What does exactly "adjusted values" mean?

thank you in advance!

**Comment by konradjk** [comment]
This corresponds to AC_Adj in the ExAC VCF, which only includes individuals with at least GQ (Genotype Quality) >= 20 and depth >= 10, described in the README on the FTP site: ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3/README.population_annotations
