### ISSUE TITLE
when you search for chr:pos sometimes a filtered variant won't show

### ISSUE THREAD

**Issue by macarthurlab** [konradjk/exac_browser#177]
see <http://exac.broadinstitute.org/variant/20-4680025-C-T> and then <http://exac.broadinstitute.org/region/20-4680025-4680025> (Created by ericminikel from macarthurlab Slack)

**Comment by ericminikel** [comment]
Additional example from @dgmacarthur 

bizarrely, if you search a range that *includes* the filtered site, and then tick the box, it shows

dgmacarthur [2:41 PM]
http://exac.broadinstitute.org/region/1-55505593-55505613

dgmacarthur [2:42 PM]
vs http://exac.broadinstitute.org/region/1-55505603-55505603
