### ISSUE TITLE
Export to CSV gives all columns for some genes, only some columns for other genes

### ISSUE THREAD

**Issue by ericminikel** [konradjk/exac_browser#183]
This morning I received this note from Steven Harrison at LMM and I have been able to reproduce the error with _GJB2_ and _USH2A_.

> Morning:
> 
> Got a question about downloading the variant list for a given gene – sometimes the “Export table to CSV” includes the allele counts and allele numbers for all populations (such as GJB2 gene) and sometimes the export only includes the total aggregated allele counts and allele numbers (such as the USH2A gene). Is this due to the gene size? As part of our gene assessment process we determine how many variants of each variant type have a MAF >0.3% in any population, but for genes like USH2A and RYR2 we’re unable to get the population breakdown in the export.
> 
> Thanks for any help!
>  
> -Steven

**Comment by konradjk** [comment]
Done - required a reload of the cache since updating the export function.
