### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by rmhasle** [konradjk/exac_browser#188]
The peptide predictions for the following and many more variants that I have looked at in LDLR are incorrect
19:11201275 A / T , 19:11230785 A / T , 19:11230797 C / T (rs137853962) , 19:11230809 C / T ,19:11230833 C / T , 19:11230842 C / T (rs5926) , 
All the amino acid predictions from the start of exon 17 are incorrect (from variant 19:11240130 C / T )

**Comment by dgmacarthur** [comment]
Hi - again, these are not incorrect. They correspond to annotations relative to valid Gencode transcripts, although in most of the cases you note here these transcripts are poorly supported, and I expect many will be dropped in future Gencode releases. 

To view annotations relative to the canonical Gencode LDLR transcript you can instead use this page: http://exac.broadinstitute.org/transcript/ENST00000558518

**Comment by rmhasle** [comment]
Hi, thanks for your reply.  Whilst I understand that these annotations relate to valid Genecode transcripts I think it is misleading to have them listed under the heading of the LDLR gene, because they are not the accepted transcription and translation products of LDLR as widely accepted NM_000527.4

**Comment by dgmacarthur** [comment]
That transcript may be used by the US clinical community, but there is no international standard on which transcript is canonical for every gene, and RefSeq is rarely used outside the US. In addition, there is no easy way to map from RefSeq transcripts to Gencode across all genes.

More seriously, there is a problem with only showing a single transcript on the gene page: this would mean that genuinely functional variants affecting other transcripts would not be shown at all in the gene summary. The best workaround for this problem that we have discovered so far is to use the worst annotation across all transcripts for each variant. This results in weirdness in many edge cases, but overall works better than the alternatives.

Again, if you wish to view a specific transcript that option is freely available on the browser. For users with interest in a specific gene we think this should be a quick and relatively painless approach.
