### ISSUE TITLE
Feature Request: LD information

### ISSUE THREAD

**Issue by dhimmel** [konradjk/exac_browser#189]
Hi ExAC team, I am interested in finding all SNPs in LD (linkage disequilibrium) with a query SNP. Specifically, I am looking for a service like the [SNAP proxy search](https://www.broadinstitute.org/mpg/snap/ldsearch.php) that is built from more comprehensive data than the 1000 Genomes Pilot. Your resource was [suggested to us](http://thinklab.com/discussion/calculating-genomic-windows-for-gwas-lead-snps/71#240) as a newer alternative.

Do you have any whole-genome sequences that allow you assess SNPs outside of the exome? Also, do you plan to release any of the LD information in your *massive genome assemblage*?

**Comment by konradjk** [comment]
Unfortunately, we have no plans to do this at the present time - we do not yet have enough whole genome sequences to create a scaffold.
