### ISSUE TITLE
Wrong aa deletion?

### ISSUE THREAD

**Issue by patrickbryant1** [konradjk/exac_browser#190]
Many inframe deletions of CCA on the page: http://exac.broadinstitute.org/gene/ENSG00000100811 (regarding the YY1 protein) suggest a deletion of the amino acid histidine. CCA is the codon for proline.  Why would a CCA deletion be stated as a His deletion and not a Pro?

Patrick

**Comment by konradjk** [comment]
This is a deletion of CCA repeats, but the actual amino acids deleted are CACs - see: http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&highlight=hg19.chr14%3A100705787-100705793&position=chr14%3A100705762-100705818
