### ISSUE TITLE
ExAC 1kg data

### ISSUE THREAD

**Issue by yeinhorn** [konradjk/exac_browser#203]
I used annovar to annotate variants with 1kg european frequecny and exac NFE frequncy.
I found out that many of the variants the exist in the 1kg DB don't appear in the Exac DB.
From what i red, i understand that the 1kg DB included in the Exac DB, so how could it be?
I also checked it mannualy (to see if it's a problem with annovar) for one of the problematic snps 'rs142849724' and looked for him in the Exac browser and it seems that it couldn't find any snp like this in the DB, while it has a 0.02 frequency in 1kg.

**Comment by dgmacarthur** [comment]
The ExAC database includes the *exome* sequencing data from 1000 Genomes, not the whole-genome sequencing data. As such it is missing coverage for most non-coding regions of the genome. We recommend combining ExAC with 1000G for systematic assessment of all variation.

In the case of rs142849724 there is zero coverage in this region in our exome sequencing data: http://exac.broadinstitute.org/region/1-847681-847701
