### ISSUE TITLE
Variant not listed under gene name but present in server AND contact email not working

### ISSUE THREAD

**Issue by tugcebalci** [konradjk/exac_browser#204]
Hello,

We just figured out today that a variant that cannot be found in the list that comes up when we search with the gene name, can actually be found when you search for the actual change itself! We thought this would be an important bug, if it is, as we always search for variants in the list, rather than checking the variant itself with the genomic designation. Can you please clarify? 

Here is the variant:

Gene: NOTCH1 
NM_017617.3 
c.581C>T:pThr194Ile 

Chromosomal variant:
NC_000009.11:g.139417463G>A

I’m attaching the screenshots for your reference. 

Thank you,

Tugce B. Balci, MD
Resident in Medical Genetics, PGY4
University of Ottawa
Children’s Hospital of Eastern Ontario
401 Smyth Road K1H 8L1
Ottawa, ON CANADA
+1-613-737-7600 x:2964

![exac screen shots for notch1 1](https://cloud.githubusercontent.com/assets/13892924/9394144/b69654f4-4754-11e5-8b3c-2e1e242c28c6.JPG)
![exac screen shots for notch1 2](https://cloud.githubusercontent.com/assets/13892924/9394142/b691d140-4754-11e5-936d-b65849e86684.JPG)
![exac screen shots for notch1 3](https://cloud.githubusercontent.com/assets/13892924/9394143/b6953b96-4754-11e5-8e38-a2b4ecaaf636.JPG)
![exac screen shots for notch1 4](https://cloud.githubusercontent.com/assets/13892924/9394145/b6973590-4754-11e5-9cbc-e94d957f6b9d.JPG)

**Comment by tugcebalci** [comment]
Also, I tried emailing this to the "contact" address exac.data@gmail.com and received an error message, saying there's a problem with the recipient's mailbox.

**Comment by konradjk** [comment]
The variant you mention is filtered out by VQSR (Note the VQSRTranche... on the right side of the page). You can see these variants if you click "Include filtered (non-PASS) variants" at the top of the table.

The email is indeed an issue - we will fix that.

**Comment by tugcebalci** [comment]
Wow that was fast. Thank you. Good to know.
