### ISSUE TITLE
Allele count not integer in v0.3

### ISSUE THREAD

**Issue by lfearnley** [konradjk/exac_browser#210]
Hi,

Some of the AC fields in the v0.3 data (in the file 'ExAC.r0.3.sites.vep.vcf') have commas (minimal example follows). I was expecting integers from the INFO header, rather than a list - is this intended/is there documentation somewhere for this behaviour?

Best,

Liam

Example:

##INFO=\<ID=AC_AFR,Number=A,Type=Integer,Description="African/African American Allele Counts">

1	865693	.	G	A,GCA	1293.35	VQSRTrancheINDEL97.00to99.00	AC=5,1;AC_AFR=0,0;AC_AMR=0,0;AC_Adj=2,1;AC_EAS=0,0;AC_FIN=2,0;AC_Het=2,1,0;AC_Hom=0,0;AC_NFE=0,0;AC_OTH=0,0;AC_SAS=0,1

**Comment by dgmacarthur** [comment]
Hi - this is the standard VCF specification for a site with more than one non-reference allele. In this case you can see from the fifth field that there are two different non-reference alleles at this site (A and GCA) - i.e. there is a G > A SNP, and a CA insertion. All of the following INFO tags are comma-divided to provide information separately about these two alleles, e.g. the AC is 5 for the SNP and 1 for the insertion.

You can learn more than you ever wanted to know about VCF file specifications here: http://samtools.github.io/hts-specs/VCFv4.2.pdf
