### ISSUE TITLE
Connection error at ftp://ftp.broadinstitute.org/pub/ExAC_release/current

### ISSUE THREAD

**Issue by raphael0202** [konradjk/exac_browser#213]
The provided link of the database doesn't work:
ftp://ftp.broadinstitute.org/pub/ExAC_release/current

**Comment by konradjk** [comment]
Does it still not work for you? Seems to have been working fine for us today, perhaps it was a temporary outage?

**Comment by raphael0202** [comment]
It works for me now, it may have been indeed 
a temporary outage
