### ISSUE TITLE
Page not found when requesting a variant

### ISSUE THREAD

**Issue by raphael0202** [konradjk/exac_browser#214]
I get a 404 error when requesting the following variant: 9-101867486-C-T
http://exac.broadinstitute.org/variant/9-101867486-C-T

**Comment by konradjk** [comment]
I've tracked down the issue and will push a fix some time this week. Basically, it's a garbage variant in the first place (AN_Adj = 0, which means no single individual in ExAC had depth > 10 and GQ > 20 at this position), and the site had troubles dividing by zero.
