### ISSUE TITLE
About ExAC's fields interpretation

### ISSUE THREAD

**Issue by chulghim** [konradjk/exac_browser#230]
1 13402 . G C 89.66 VQSRTrancheSNP99.60to99.80 AC=2;AC_AFR=0;AC_AMR=0;AC_Adj=0;AC_EAS=0;AC_FIN=0;AC_Het=0;AC_Hom=0;AC_NFE=0;AC_OTH=0;AC_SAS=0;AF=1.078e-04;AN=18552;AN_AFR=154;AN_AMR=20;AN_Adj=1476;AN_EAS=64;AN_FIN=0;AN_NFE=320;AN_OTH=20;AN_SAS=898;DP=38807;FS=0.000;GQ_MEAN=8.99;GQ_STDDEV=9.11;Het_AFR=0;Het_AMR=0;Het_EAS=0;Het_FIN=0;Het_NFE=0;Het_OTH=0;Het_SAS=0;Hom_AFR=0;Hom_AMR=0;Hom_EAS=0;Hom_FIN=0;Hom_NFE=0;Hom_OTH=0;Hom_SAS=0;

In this case, AC_Het=0

But, 
1 13404 . G A,T 136.58 VQSRTrancheSNP99.60to99.80 AC=2,1;AC_AFR=0,0;AC_AMR=0,0;AC_Adj=0,1;AC_EAS=0,0;AC_FIN=0,0;AC_Het=0,1,0;AC_Hom=0,0;AC_NFE=0,0;AC_OTH=0,0;AC_SAS=0,1;AF=1.078e-04,5.391e-05;AN=18548;AN_AFR=142;AN_AMR=20;AN_Adj=1384;AN_EAS=62;AN_FIN=0;AN_NFE=300;AN_OTH=18;AN_SAS=842;BaseQRankSum=-2.780e-01;ClippingRankSum=0.896;DP=38414;FS=0.000;GQ_MEAN=8.90;GQ_STDDEV=9.04;Het_AFR=0,0,0;Het_AMR=0,0,0;Het_EAS=0,0,0;Het_FIN=0,0,0;Het_NFE=0,0,0;Het_OTH=0,0,0;Het_SAS=0,1,0;Hom_AFR=0,0;Hom_AMR=0,0;Hom_EAS=0,0;Hom_FIN=0,0;Hom_NFE=0,0;Hom_OTH=0,0;Hom_SAS=0,0;

**In this case, AC_Het=0,1,0 => why 3 values? **

According to this vcf header, right values are 1,0 ?

Header definition is the following
INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
INFO=<ID=AC_AFR,Number=A,Type=Integer,Description="African/African American Allele Counts">
NFO=<ID=AC_AMR,Number=A,Type=Integer,Description="American Allele Counts">
NFO=<ID=AC_Adj,Number=A,Type=Integer,Description="Adjusted Allele Counts">
INFO=<ID=AC_EAS,Number=A,Type=Integer,Description="East Asian Allele Counts">
INFO=<ID=AC_FIN,Number=A,Type=Integer,Description="Finnish Allele Counts">
INFO=<ID=AC_Hemi,Number=A,Type=Integer,Description="Adjusted Hemizygous Counts">
INFO=<ID=AC_Het,Number=A,Type=Integer,Description="Adjusted Heterozygous Counts

**Comment by konradjk** [comment]
Yes, this is a known issue (#164) - the number of values is correct, but it shouldn't be Number=A. This will be fixed when we push a new VCF hopefully fairly soon.

**Comment by konradjk** [comment]
This has now been fixed in release 0.3.1: ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1
