### ISSUE TITLE
Read Data Visualization Issue

### ISSUE THREAD

**Issue by Massimo78** [konradjk/exac_browser#231]
Dear ExAC supporting team,

I would like to check if a candidate pathogenic variant we found in our study (which is a ultra rare variant in ExAC, allele count =7) is or not coupled to another variant on the same gene in any of the seven samples matched in ExAC browser. I tried using the Read Data Visualization tool but I got some problems (no more than four samples can be visualized  when I change genomic location)
Any help will be appreciated
Thank you in advance

Massimo Acquaviva

Bioinformatician
UOC Medical Genetics
Giannina Gaslini Institute
Genova, Italy

**Comment by konradjk** [comment]
Unfortunately, we don't have support for more data on the browser. Can you email exomeconsortium@gmail.com with the 2 variants you are interested in and we can try to help there?

**Comment by Massimo78** [comment]
Dear Konrad,
thank you so much for your reply.

We would like to check if a candidate pathogenic variant we found in our
study (which is a ultra rare variant in ExAC, allele count =7) is or not
coupled to another variant on the same gene in any of the seven samples
matched in ExAC browser
The two variants are both in TECPR2 gene :  14-102906902-C-T     T903M
and         14-102901204-C-G   L684V (rs45467297)

If it' s not a problem for you we'd like also to know if the variant  16-
89597127-G-A  G300R  in SPG7 gene  ( found in  two samples in ExAC) is
present togheter with the variant  14-102906902-C-T     T903M    in any of
the two samples.

Thank you in advance

Massimo Acquaviva & Angela Covone

UOC Medical Genetics
Gaslini Institute
Genova Italy


2016-03-10 23:48 GMT+01:00 Konrad Karczewski <notifications@github.com>:
