### ISSUE TITLE
gene.html breaks when no variants on canonical transcript

### ISSUE THREAD

**Issue by pontikos** [konradjk/exac_browser#232]
I have forked exac_browser to use it on our variant database.
I got an error on accessing the gene page for ENSG00000198822 because none of the variants in our database are on the canonical transcript ENST00000361669.

This breaks this line in the ```gene.html``` template code because ```variants_in_transcript``` is empty:
```
                <div class="row">
                    {% if variants_in_gene %}
                        {% set chrom = variants_in_transcript[0].chrom %}
                        {% include 'variant_table.html' %}
                    {% else %}
                        No variants in this gene.
                    {% endif %}
                </div>
```

This  error might have surfaced because I'm using VEP82 and the canonical transcript might have changed from what is in ```canonical_transcripts.txt.gz```

Why not just change it to:
```
                <div class="row">
                    {% if variants_in_transcript %}
                        {% set chrom = variants_in_transcript[0].chrom %}
                        {% include 'variant_table.html' %}
                    {% else %}
                        No variants in this gene.
                    {% endif %}
                </div>
```

**Comment by pontikos** [comment]
I have committed a fix to my fork of your browser:
https://github.com/pontikos/uclex_browser/commit/b50b2e73f83c62db4f499233872961c1f11888ad

I can't figure out how to make a pull request of just that commit.
I don't want to make pull requests for my other commits since I'm making substantial changes to the code for our use.

By the way thank you very much for your excellent work, your code is proving to be an excellent platform for our purpose..

**Comment by pontikos** [comment]
ok I have figure how to do so http://stackoverflow.com/questions/34027850/how-to-pull-request-a-specific-commit

please accept my pull request

Many Thanks!

Nikolas.

**Comment by pjvandehaar** [comment]
Sorry, I'm looking at pulling this change into our fork of the browser.  To me,

```
                    {% if variants_in_gene and variants_in_gene[0].chrom %}
                        {% set chrom = variants_in_gene[0].chrom %}
                        {% include 'variant_table.html' %}
```

seems like a better fix than

```
                    {% if variants_in_transcript %}
                        {% set chrom = variants_in_transcript[0].chrom %}
                        {% include 'variant_table.html' %}
```

Am I missing something?

While we're at it, it's better namespacing to use 

```
                {% if variants_in_gene and variants_in_gene[0].chrom %}
                    {% with chrom = variants_in_gene[0].chrom %}
                        {% include 'variant_table.html' %}
                    {% endwith %}
```

**Comment by pontikos** [comment]
mmm probably, if that still works when another transcript is selected, fine
by me.

**Comment by pjvandehaar** [comment]
Sorry, I'm not sure what you mean by selecting another transcript.  This is on `gene.html`, where the canonical transcript is always selected, right?  My version is too different from the others, so my assumptions sometimes don't hold.

**Comment by pontikos** [comment]
Ah ok, if that's the case then I think your change is fine.

**Comment by pjvandehaar** [comment]
Thanks for confirming I'm not missing anything obvious here.
