### ISSUE TITLE
The variant page's Genotype Quality Metrics graph is broken.

### ISSUE THREAD

**Issue by pjvandehaar** [konradjk/exac_browser#235]
When I click a toggle-button on that graph, the console prints:

    cannot call methods on button prior to initialization; attempted to call method 'toggle'

I found [this stackoverflow page](http://stackoverflow.com/questions/13235578/bootstrap-radio-buttons-toggle-issue) which says that it happens when you load jquery-ui after bootstrap3, which indeed you are doing because of IGV.

Good luck– I don't see an elegant solution to this problem.

**Comment by sdevera1122** [comment]
Work around is : add "<script type="text/javascript" src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>" to variant.html page below jquery-ui.min.js at 465

**Comment by sdevera1122** [comment]
Work around or temporary fix : load bootstrap.min.js again in variant.html below jquery-ui.min.js i.e at line 465 (https://github.com/konradjk/exac_browser/blob/master/templates/variant.html#L465)

**Comment by konradjk** [comment]
Coming back around to this. Moving the jquery-ui loads to after jquery and before bootstrap seems to solve this problem too. Can anyone foresee a reason why this would be a problem?

**Comment by sdevera1122** [comment]
I did try it on my local instance and found no problem.

**Comment by pjvandehaar** [comment]
IGV still works fine?

**Comment by sdevera1122** [comment]
Yes. I made few changes to IGV so it loads my own bam but everything seems
to work fine.

**Comment by pjvandehaar** [comment]
I see bug reports related to close buttons when you load bootstrap after jqueryui.  Maybe check those on a couple browsers.

**Comment by konradjk** [comment]
Well, on the plus side, I can ensure that this load only happens on variant.html and that doesn't have any buttons.

**Comment by pjvandehaar** [comment]
Sorry, I mis-spoke.  I meant to say the opposite: if you load bootstrap after jqueryui, bootstrap overwrites some button-related functions.  So, check on your IGV buttons, particularly the close buttons on the popup/dialog boxes.

**Comment by konradjk** [comment]
Looks good at first glance, though the only dialog i can think of are the ones when you click on reads and the settings - any others?

**Comment by pjvandehaar** [comment]
That's all.  Sounds good.
