### ISSUE TITLE
Why are you leaving out the first consequence?

### ISSUE THREAD

**Issue by pjvandehaar** [konradjk/exac_browser#246]
See <https://github.com/konradjk/exac_browser/blob/75d2262ad59d97900fe382127ff18305030270b1/templates/variant.html#L299>.  Why is it indexed `ordered_csqs[1:` instead of `ordered_csqs[0:`?

**Comment by konradjk** [comment]
I believe it's because this is javascript indexing? If I switch it to 0, I get the exact same thing - do you get something different?

**Comment by pjvandehaar** [comment]
It's because of <https://github.com/konradjk/exac_browser/blob/ac46a5f4e20770b781f824ad926a6d7c5baf59b3/exac.py#L553>, which makes `''` the first element of that list.

Here's how to make everything better:

1. Put the following in `utils.py`:

```
def unique_with_same_order(lst):
    unique_list = []
    for elem in lst:
        if elem not in unique_list:
            unique_list.append(elem)
    return unique_list
assert unique_with_same_order([1,2,3,2,1]) == [1,2,3]
```

2. Replace
 
> ordered_csqs = reduce(lambda x, y: ','.join([x, y]) if y not in x else x, ordered_csqs, '').split(',') # Close but not quite there

with 

>ordered_csqs = unique_with_same_order(ordered_csqs)

3. Replace `[1:` with `[:`.

**Comment by pjvandehaar** [comment]
Or, if you insist on keeping `reduce`, You could just switch that nasty line to: 

```python
reduce((lambda accum,elem: accum if elem in accum else accum+[elem]), l, [])
```

**Comment by konradjk** [comment]
That... explains a few things. I'm fine with either of those solutions - can you go ahead and PR? Thanks!

**Comment by pjvandehaar** [comment]
I lumped it into https://github.com/konradjk/exac_browser/pull/243 .
