### ISSUE TITLE
igv on local instance of exac browser

### ISSUE THREAD

**Issue by sdevera1122** [konradjk/exac_browser#249]
Hi,

Im working on creating local instance of exac browser hosting my exome data. So far i was successful in creating the instance but the IGV.js plugin on variants page doesnt load as there is no bam/alignment data loaded. Can you please let me know how to load our read/alignment data so i can get IGV.js working on our instance.

Thanks

**Comment by bw2** [comment]
Hi @sdevera1122 ,  if you want to show your own .bam or .bed files in the browser, you can simply make them (along with their .bai and .idx indexes) available through an http server like apache, and then point the browser to their urls like here: https://github.com/konradjk/exac_browser/blob/master/templates/variant.html#L534

If you want to first convert your raw bams to reassembled bams by running GATK HaplotypeCaller, you can see the code we used to do this here: https://github.com/macarthur-lab/exac_readviz_scripts

**Comment by sdevera1122** [comment]
Thanks and this link (https://github.com/macarthur-lab/exac_readviz_scripts) doesn't work.

**Comment by bw2** [comment]
Sorry. I forgot that repo was private. I've made it public now if you want to take another look..

**Comment by sdevera1122** [comment]
thanks
