### ISSUE TITLE
md5sum file for SUBSETS not available from the ftp repository

### ISSUE THREAD

**Issue by mbelmadani** [konradjk/exac_browser#254]
I'm trying to download:
ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3/subsets/md5sum.txt

But I keep getting an ERR_FTP_FAILED error.

That's only for the **subsets**, the md5sums for the full other datasets seem to work (For example, ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3/md5sum.txt)

**Comment by monkollek** [comment]
Thanks for the feedback. I have changed the file permissions and it works now.
