### ISSUE TITLE
Missing mutation

### ISSUE THREAD

**Issue by EGillis42** [konradjk/exac_browser#261]
Hello,

The mutation chr15:66995669 GGCGGCA>G is not present on the Exac webpage of SMAD6. Although the mutation page exists: http://exac.broadinstitute.org/variant/15-66995669-GGCGGCA-G

Thanks!

**Comment by pontikos** [comment]
Have you checked the filtered variants?
Variants which don't have a PASS in the filter field are not displayed by
default.

**Comment by dgmacarthur** [comment]
Yes, Nikolas is correct - the variant is present on the gene page, but filtered. You can see filtered variants by ticking the "Include filtered (non-PASS) variants" box above the variant table.

**Comment by EGillis42** [comment]
Thank you!
