### ISSUE TITLE
VCF format issue

### ISSUE THREAD

**Issue by pfsulliv** [konradjk/exac_browser#269]
Hi - this is in reference to an issue in r0.3 that was said to be fixed in r.0.3.1. See
https://github.com/konradjk/exac_browser/issues/164
https://github.com/konradjk/exac_browser/issues/230

Am using the r0.3.1 sites file
ftp://ftp.broadinstitute.org/pub/ExAC_release/current/ExAC.r0.3.1.sites.vep.vcf.gz

and getting errors in AC_Het for sites with more than one allele in the ALT field. 

INFO=
ID=AC_Het,Number=A,Type=Integer,Description="Adjusted Heterozygous Counts"

Examples of errors from vcf-validator and the vcf rows
INFO field at 1:13528 .. INFO tag [AC_Het=13,9,0] expected different number of values (expected 2, found 3)
INFO field at 1:17478 .. INFO tag [AC_Het=24,1,0] expected different number of values (expected 2, found 3)
1       13528   .       C       G,T     1771.54 VQSRTrancheSNP99.60to99.80      ... AC_Het=13,9,0;
1       17478   .       C       T,G     4659.13 PASS    ... AC_Het=24,1,0;

Should the tag be AC_Het,Number=R? 

thx, pfs

**Comment by pfsulliv** [comment]
Oops. just saw https://github.com/konradjk/exac_browser/issues/256, same issue

**Comment by konradjk** [comment]
This is now fixed with release 1.0 - sorry for the delay!
