### ISSUE TITLE
correction LoF for NR1F3 protein also called RORC or ROR gamma

### ISSUE THREAD

**Issue by RafMack** [konradjk/exac_browser#278]
Hi, 
I noticed that "LoF" should be 2 counts instead of 1 for the NR1F3 protein also called RORC. There is 1 stop gained and 1 splice donor. Please check link below. 

http://exac.broadinstitute.org/gene/ENSG00000143365.

Thank you. 
Kind regards, 
Rafah Mackeh.

**Comment by RafMack** [comment]
Sorry. the stop gained has AF>0.002 so it is not counted.

**Comment by s-wang5** [comment]
Hi,
I know it's an issue long time ago. But I found there is another frameshift variant using the link RafMack mentioned. Did you update the database recently or you actually ignored the frameshift when count LoF? Thanks!
Best regards,
Sheng
