### ISSUE TITLE
Newest version size too small

### ISSUE THREAD

**Issue by xtmgah** [konradjk/exac_browser#288]
Hello:

I have a simple question, Under ftp site, the file size for ExAC.r0.3.1.sites.vep.vcf.gz only have 45.4MB?, while, it should be at least few GB. but i found file size for ExAC.r0.3.sites.vep.vcf.gz about 3.18 GB. So, something wrong with ExAC.r0.3.1.sites.vep.vcf.gz? 

Thanks.

**Comment by brunobowden** [comment]
This shows as 4.0GB to me, accessing the FTP site through Chrome. See screenshot:

![screen shot 2016-09-29 at 6 50 13 pm](https://cloud.githubusercontent.com/assets/679339/18978289/c5cb4af8-8676-11e6-8abc-d6094e6a5b1b.png)

**Comment by brunobowden** [comment]
Note, this was at the following URL:
ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/
