### ISSUE TITLE
Definition of LoF

### ISSUE THREAD

**Issue by tadafumikato** [konradjk/exac_browser#312]
In the FAQ section, the definition of LoF says "Nonsense, splice acceptor, and splice donor variants caused by single nucleotide changes". Frameshift is missing here, and because of this, the definition is discordant with that in your paper.

**Comment by ksamocha** [comment]
That definition of LoF only applies to the constraint analyses (e.g. pLI). Other analyses in the paper include frameshift variants.

**Comment by tadafumikato** [comment]
Thank you for your quick response! I was confused because the paper says "This metric - the probability of being loss-of-function (LoF) intolerant (pLI) - (p288)" just after the description of PTVs, which was later defined as "a stop codon, frameshift, or the disruption of an essential splice site (p.289)". But now I understand that the definition is different between these two. I appreciate your comments.
