### ISSUE TITLE
Hemizygous variants on chromosome X

### ISSUE THREAD

**Issue by sn4** [konradjk/exac_browser#317]
Hi, 

On the Exac website, can the hemizygous variants on chrX be presumed to be males and homozygous variants presumed to be females?

Its not clear on the web interface nor is there a break up available for variants that are male or female.

Shailender Nagpal

**Comment by konradjk** [comment]
Yes, exactly! Hemizygous are males, homozygous are females (and by extension, you can compute heterozygous females as: `Allele Count - Hemizygous - 2*Homozygous`).
