### ISSUE TITLE
TTN gene results not displayed

### ISSUE THREAD

**Issue by jjfarrell** [konradjk/exac_browser#347]
When searching for the TTN gene, nothing is returned. It appears to be timing out. This is a very large gene with lots of variants.  The largest gene DMD  does display despite its size.

**Comment by mattsolo1** [comment]
Hi, you can access TTN data at the gnomAD beta browser: http://gnomad-beta.broadinstitute.org/gene/TTN

**Comment by jjfarrell** [comment]
Thanks but I wanted to lookup the gene missense constraint metric which is not available on gnomAD yet.

**Comment by mattsolo1** [comment]
You can switch the dataset to ExAC to see constraint. The UI is a bit confusing but this will change soon.

![image](https://user-images.githubusercontent.com/8867295/45649366-19c67800-ba99-11e8-9757-096ffa51896d.png)

**Comment by jjfarrell** [comment]
Thanks!
